### ISSUE TITLE
The SIGWINCH signal

### ISSUE THREAD

**Issue by neo954** [xcat2/goconserver#10]
This bug is against `goconserver` `Version: 0.1, BuildTime: 2017-11-07T23:00:03-0500 Commit: 906cd810f009dd1b0b22a75ea0c4efc1cbb2e840` running on a ppc64le Red Hat 7.4 Linux environment.

**The recreation steps**

Create a node definition in `congo`. And then connect to the newly created node. BTW, the node, `c910f03c01p09` is just another common Linux node, which runs Red Hat 7.4.

```
# congo create c910f03c01p09 driver=ssh ondemand=false \
> --params user=root,host=10.3.1.9,port=22,password=a_password
# congo console c910f03c01p09
goconserver(2017-11-08 00:16:57): Hello 127.0.0.1:57304, welcome to the session of c910f03c01p09
```

Run `nano` through the console session.

<img width="586" alt="screen shot 2017-11-15 at 16 43 51" src="https://user-images.githubusercontent.com/12424088/32826682-fd77761c-c9ae-11e7-8585-e61659317fcd.png">

Resize the terminal window. And all the screen display messed up.

<img width="378" alt="screen shot 2017-11-15 at 16 44 41" src="https://user-images.githubusercontent.com/12424088/32826706-15c3e048-c9af-11e7-86e7-7e3d1100d8e5.png">

**What actually happened**

The `SIGWINCH` signal was not handled properly

**What is expected**

* See [RFC 4254](https://www.ietf.org/rfc/rfc4254.txt), section 6.7

**Comment by chenglch** [comment]
I have upload ce1920e9d1ef25c26d1ca00ff31cb52bb1e4f385 to leverage the default signal handler for SIGWINCH. This commit could not solve this issue.

I checked how `conserver`work for this, it also does nothing for SIGWINCH signal either. The display format after window change event depends on the protocol under the console session. For example , `ssh` or `kvm console` is different. 

I will look it as a feature request if I could find a better solution for it in the future.
