### ISSUE TITLE
Consider log rotate

### ISSUE THREAD

**Issue by neo954** [xcat2/goconserver#11]
This is a feature request.

Currently, there is no way to do log rotate against the console logs. `goconserver` need to provide a method to let the end user to log rotate against the console logs. Otherwise, all the logs will fill up `/var` file system, eventually.

Either provide a mechanism to work with `logrotate` or do the log rotate inside `goconserver` will be fine.

To work with `logrotate`. Do the following ...
* Register a signal handler for, say `SIGHUP` or `SIGUSR1`.
* When the corresponding signal is caught, close all the opened log files, and then reopen all the log files with the same file names.
  - Don't lose log entries in this step.
  - The main log file, should rotate as well.

**Comment by chenglch** [comment]
I think current implementation could support `logrotate` as O_APPEND flag is used to write to the log file. You could have a try about this.

If not,  I could consider a framework to implement this including the log redirection to support some big data solution mentioned by @whowutwut .

**Comment by neo954** [comment]
Based on my test, all console log files under `/var/log/goconserver/nodes` can do log rotate just fine. But the main server log, `/var/log/goconserver/server.log` is not work with log rotate right now.

**Comment by chenglch** [comment]
The log rotate support with HUP signal has been added within the commit of a0cd2655cb66b7f5befaf7b672482ff15a834a80

**Comment by neo954** [comment]
Verified with `goconserver-0.2.1-snap201803020124.ppc64le`. I will close this one.
