### ISSUE TITLE
When console is not created, the error message doesn't help user

### ISSUE THREAD

**Issue by whowutwut** [xcat2/goconserver#13]
Should this be opened on xcat-core? or here? 

Trying to open console on mic05tor12cn15.

```
[root@briggs01 ~]# rcons mid05tor12cn15


Could not find node mid05tor12cn15
```

Maybe we could do better.... 

`Could not find node mid05tor12cn15, did you run 'makegocons mid05tor12cn15'? `

After running, it is OK

```
[root@briggs01 ~]# makegocons mid05tor12cn15
mid05tor12cn15: Created
[root@briggs01 ~]# rcons mid05tor12cn15
[Enter `^Ec?' for help]
goconserver(2017-12-08 14:45:22): Hello 172.10.253.27:34166, welcome to the session of mid05tor12cn15

Red Hat Enterprise Linux Server 7.4 Beta (Maipo)
Kernel 4.11.0-39.el7a.ppc64le on an ppc64le

mid05tor12cn15 login:
```

**Comment by chenglch** [comment]
Thanks @whowutwut, for xcat user this is helpful, But I can not modify the message in `goconserver` directly as there are other methods like `REST` or `congo` command to register the console session into `goconserver`. 

I plan to modify the `rcons` in xcat side to transfer a environment to `congo` command which will make `goconserver` aware of the existence of xcat, and then print the message like you suggested.

**Comment by neo954** [comment]
Verified with `goconserver-0.2.1-snap201803020124.ppc64le`. I will close this one.
