### ISSUE TITLE
TCP output contains carriage returns at the end of message

### ISSUE THREAD

**Issue by mattaezell** [xcat2/goconserver#18]
I have TCP hooked up to `rsyslog`.  It seems that newlines are not included in the output, but carriage returns are.  I would expect both to be stripped.
```
{"type": "console","message":"[30595.853585] Policy zone: DMA\r","node":"h41n01","date":"2018-01-29 16:40:10.62790"}
```

**Comment by mattaezell** [comment]
Confirmed:
`inputname: imtcp rawmsg: '{"type":"console","message":"hello","node":"h41n02","date":"2018-02-01 20:02:44.502970"}'`
Thanks!

**Comment by neo954** [comment]
Verified with `goconserver-0.2.1-snap201803020124.ppc64le`. I will close this one.
