### ISSUE TITLE
RPM upgrade overwrites server.conf

### ISSUE THREAD

**Issue by mattaezell** [xcat2/goconserver#20]
https://github.com/chenglch/goconserver/blob/9781bc648ae76cb256af3a01a58f0274e9d091f0/dirty-rpmbuild#L114

Can this be marked `%config(noreplace)`?

**Comment by chenglch** [comment]
@neo954 , could you add a fix to handle this temporarily ? I think `/etc/profile.d/congo.sh` is also affected.

In our official build which will be integrated with xcat, I think a script will be added to help generate the configuration file.

**Comment by mattaezell** [comment]
Confirmed with 4c92228

**Comment by neo954** [comment]
Verified against both RPM and DEB package. I will close this one.
