### ISSUE TITLE
clean up consoles that no longer have xCAT node definitions

### ISSUE THREAD

**Issue by whowutwut** [xcat2/goconserver#29]
Some sort of cleanup is required to remove consoles that are not there anymore. 

In discovery, the `node-XXX` discovered definitions are automatically removed from the xCAT database, but a user could have ran `makegocons` and created consoles for these....

```
[root@briggs01 log]# makegocons -d node-8335-gtc-785262a
Error: Invalid nodes and/or groups in noderange: node-8335-gtc-785262a
[root@briggs01 log]# nodels | grep node-8335-gtc-785262a
[root@briggs01 log]#
```

However, the console configuration still exists so I am able to open an rcons session:
```
[root@briggs01 log]# rcons node-8335-gtc-785262a
{"file":"github.com/xcat2/goconserver/console/client.go (296)","level":"error","msg":"Fatal error: Could not connect to node-8335-gtc-785262a\n","node":"node-8335-gtc-785262a","time":"2018-02-27T16:11:45-05:00"}
The connection is disconnected
[Enter `^Ec.' to exit]
Session is teminated unexpectedly, retrying....
```

How do we get rid of these in gocons? 
The good thing is that no logs write to here, so the log does not keep growing....

We had a similar thing in `makeconservercf --cleanup` function...

**Comment by chenglch** [comment]
This is a history problem from xcat, xcat allows to delete the node but do not help clean up the resource owned by the node.
I will add `makegocons --cleanup` like `makeconservercf --cleanup`.
