### ISSUE TITLE
goconserver need to restart after upgraded

### ISSUE THREAD

**Issue by zet809** [xcat2/goconserver#49]
In v0.3.1, we have include the fix #46 , but fix will only work after goconserver is restarted.

We need to add `prerm` script to cleanup goconserver service, and `postinst` to restart goconserver after updated.

**Comment by zet809** [comment]
The issue https://github.com/xcat2/xcat-core/issues/5564 have more information, pls reference it for this issue. Thx!

**Comment by zet809** [comment]
Fix this issue in #53  for rpm part.
For deb part, @neo954  will cover.

**Comment by neo954** [comment]
Verified on `goconserver-0.3.2-snap201811080416.ppc64le`. This issue was fixed.

**Comment by neo954** [comment]
I will close this one.
