### ISSUE TITLE
`congo delete .` always success

### ISSUE THREAD

**Issue by neo954** [xcat2/goconserver#5]
This bug is against `goconserver` `Version: 0.1, BuildTime: 2017-11-07T23:00:03-0500 Commit: 906cd810f009dd1b0b22a75ea0c4efc1cbb2e840` running on a ppc64le Red Hat 7.4 Linux environment.

**The recreation steps**

```
# congo list
c910f03c01p09 (host: 127.0.0.1)
c910f03c17 (host: 127.0.0.1)
# congo delete .
Deleted
# echo $?
0
# congo list
c910f03c01p09 (host: 127.0.0.1)
c910f03c17 (host: 127.0.0.1)
```

**What actually happened**

The command, `congo delete .` actually delete nothing. But it get a positive response. And the exit code is zero.

What is expected

* A proper error message.
* Non-zero exit code.

**Comment by neo954** [comment]
Create a node named `.` and it cannot be deleted any more.

```
# congo create . driver=ssh ondemand=false \
> --params user=root,host=10.3.1.9,port=22,password=foobar
Created
# congo list
c910f03c01p09 (host: 127.0.0.1)
c910f03c17 (host: 127.0.0.1)
. (host: 127.0.0.1)
# congo delete .
Deleted
[root@c910f03c17k04 ~]# congo list
c910f03c17 (host: 127.0.0.1)
. (host: 127.0.0.1)
c910f03c01p09 (host: 127.0.0.1)

**Comment by robin2008** [comment]
congo delete .
Error: node name could not start with '.' or '/'
[root@c910f03c05k20 ~]# congo delete abc

Error: response == 400 bad request
