### ISSUE TITLE
Nodes listed in random sequence with `congo list` 

### ISSUE THREAD

**Issue by neo954** [xcat2/goconserver#7]
This bug is against `goconserver` `Version: 0.1, BuildTime: 2017-11-07T23:00:03-0500 Commit: 906cd810f009dd1b0b22a75ea0c4efc1cbb2e840` running on a ppc64le Red Hat 7.4 Linux environment.

**The recreation steps**

```
# for node in foo{000..999}
> do
>     congo create $node driver=ssh ondemand=false \
>         --params user=foo,host=10.3.1.9,port=22,password=something
>     congo logging $node on
> done
# congo list
foo932 (host: 127.0.0.1)
foo948 (host: 127.0.0.1)
foo888 (host: 127.0.0.1)
<<...omit...>>>
foo081 (host: 127.0.0.1)
# congo list
foo941 (host: 127.0.0.1)
foo619 (host: 127.0.0.1)
foo398 (host: 127.0.0.1)
<<...omit...>>>
foo939 (host: 127.0.0.1)
```

**What actually happened**

I created 1,000 node definitions in `congo`. Each time when I run `congo list`, it listed all nodes in a totally different random sequence.

**What is expected**

* Some kind of sorting algorithm may helpful.

**Comment by gurevichmark** [comment]
Output from `congo` command are not important, since the output from `makegocons -q` are correct.
